### ISSUE TITLE
Rename the development branch as main and make it be the default one

### ISSUE THREAD

**Issue by bcogrel** [noi-techpark/it.bz.opendatahub.kg#10]
Hi @Piiit , would it be possible to apply the new conventions to this repository?

That would also help us to share the code base more easily, by pointing people to the default branch.

Best,
Benjamin

**Comment by Piiit** [comment]
@bcogrel Done, we have a `main` branch for development now, and a `prod` for the production releases... The `main` is also the default now

**Comment by bcogrel** [comment]
Thanks!
